services:

  #  ███╗   ██╗███████╗██╗  ██╗████████╗ ██████╗██╗      ██████╗ ██╗   ██╗██████╗
  #  ████╗  ██║██╔════╝╚██╗██╔╝╚══██╔══╝██╔════╝██║     ██╔═══██╗██║   ██║██╔══██╗
  #  ██╔██╗ ██║█████╗   ╚███╔╝    ██║   ██║     ██║     ██║   ██║██║   ██║██║  ██║
  #  ██║╚██╗██║██╔══╝   ██╔██╗    ██║   ██║     ██║     ██║   ██║██║   ██║██║  ██║
  #  ██║ ╚████║███████╗██╔╝ ██╗   ██║   ╚██████╗███████╗╚██████╔╝╚██████╔╝██████╔╝
  #  ╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝   ╚═╝    ╚═════╝╚══════╝ ╚═════╝  ╚═════╝ ╚═════╝
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/nextcloud:/config
      - ${MEDIA_PATH}/nextcloud:/data
    ports:
      - "8443:443"
    restart: unless-stopped
    networks:
      - nextcloud
      - proxy

  postgresql:
    image: postgres:latest
    container_name: nextcloud-postgres
    environment:
      - POSTGRES_USER=${NEXTCLOUD_DB_USER}
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - POSTGRES_DB=${NEXTCLOUD_DB_NAME}
    volumes:
      - ${CONFIG_PATH}/nextcloud/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - nextcloud

  #   ██████╗ ███╗   ██╗██╗  ██╗   ██╗ ██████╗ ███████╗███████╗██╗ ██████╗███████╗
  #  ██╔═══██╗████╗  ██║██║  ╚██╗ ██╔╝██╔═══██╗██╔════╝██╔════╝██║██╔════╝██╔════╝
  #  ██║   ██║██╔██╗ ██║██║   ╚████╔╝ ██║   ██║█████╗  █████╗  ██║██║     █████╗
  #  ██║   ██║██║╚██╗██║██║    ╚██╔╝  ██║   ██║██╔══╝  ██╔══╝  ██║██║     ██╔══╝
  #  ╚██████╔╝██║ ╚████║███████╗██║   ╚██████╔╝██║     ██║     ██║╚██████╗███████╗
  #   ╚═════╝ ╚═╝  ╚═══╝╚══════╝╚═╝    ╚═════╝ ╚═╝     ╚═╝     ╚═╝ ╚═════╝╚══════╝
  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    restart: always
    ports:
      - "8888:80"
    volumes:
      - ${CONFIG_PATH}/onlyoffice/logs:/var/log/onlyoffice
      - ${CONFIG_PATH}/onlyoffice/data:/var/www/onlyoffice/Data
    environment:
      - JWT_SECRET=${ONLYOFFICE_SECRET}
    networks:
      - nextcloud
      - proxy

networks:
  nextcloud:
    external: true
    name: nextcloud
  proxy:
    external: true
    name: proxy

