services:
  dev-container:
    image: ghcr.io/tech-dex/hiveops-dev-container:master
    container_name: dev-container
    ports:
      # SSH access
      - "2222:22"
      # Common development ports - uncomment as needed
#      - "3000:3000"   # React, Next.js default
#      - "3001:3001"   # Alternative React port
#      - "4200:4200"   # Angular default
#      - "5000:5000"   # Flask, various frameworks
#      - "5173:5173"   # Vite default
#      - "8000:8000"   # Django, FastAPI
#      - "8080:8080"   # Common web server port
#      - "8081:8081"   # Alternative web server port
#      - "9000:9000"   # Various development servers
    volumes:
      - ${WORKSPACE_PATH}/workspace:/workspace
      # You must use this path to install the jetbrains IDE, edit in the IDE settings install configuration
      - ${CONFIG_PATH}/dev-container/jetbrains:/jetbrains
      - ${CONFIG_PATH}/dev-container/ssh:/root/.ssh
      - ${CONFIG_PATH}/dev-container/openssh:/etc/ssh
      - type: bind
        source: ${CONFIG_PATH}/dev-container/bash-history
        target: /root/.bash_history
      # This is for Docker socket access, allowing the container to manage Docker available on the TrueNAS host
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - TZ=${TZ}
    networks:
      - dev_network
      - db_network

networks:
  dev_network:
    external: true
    name: dev_network
  db_network:
    external: true
    name: db_network
