services:

  #  ███████╗██████╗ ██╗ ██████╗  █████╗ ████████╗███████╗
  #  ██╔════╝██╔══██╗██║██╔════╝ ██╔══██╗╚══██╔══╝██╔════╝
  #  █████╗  ██████╔╝██║██║  ███╗███████║   ██║   █████╗
  #  ██╔══╝  ██╔══██╗██║██║   ██║██╔══██║   ██║   ██╔══╝
  #  ██║     ██║  ██║██║╚██████╔╝██║  ██║   ██║   ███████╗
  #  ╚═╝     ╚═╝  ╚═╝╚═╝ ╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚══════╝
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    stop_grace_period: 30s
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_PATH}/frigate-nvr:/config
      - ${MEDIA_PATH}/frigate-nvr:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: ${FRIGATE_RTSP_PASSWORD}
    networks:
      - nvr
      - proxy

networks:
  nvr:
    external: true
    name: nvr
  proxy:
    external: true
    name: proxy
