services:

  #   ██████╗ ██████╗ ██╗████████╗████████╗ ██████╗ ██████╗ ███╗   ██╗███████╗████████╗
  #  ██╔═══██╗██╔══██╗██║╚══██╔══╝╚══██╔══╝██╔═══██╗██╔══██╗████╗  ██║██╔════╝╚══██╔══╝
  #  ██║   ██║██████╔╝██║   ██║      ██║   ██║   ██║██████╔╝██╔██╗ ██║█████╗     ██║
  #  ██║▄▄ ██║██╔══██╗██║   ██║      ██║   ██║   ██║██╔══██╗██║╚██╗██║██╔══╝     ██║
  #  ╚██████╔╝██████╔╝██║   ██║      ██║   ╚██████╔╝██║  ██║██║ ╚████║███████╗   ██║
  #   ╚══▀▀═╝ ╚═════╝ ╚═╝   ╚═╝      ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═══╝╚══════╝   ╚═╝
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${CONFIG_PATH}/arr/qbittorrent:/config
      - ${MEDIA_PATH}/arr:/arr
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - black-sea
      - proxy

  #  ██████╗  █████╗ ██████╗  █████╗ ██████╗ ██████╗
  #  ██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗
  #  ██████╔╝███████║██║  ██║███████║██████╔╝██████╔╝
  #  ██╔══██╗██╔══██║██║  ██║██╔══██║██╔══██╗██╔══██╗
  #  ██║  ██║██║  ██║██████╔╝██║  ██║██║  ██║██║  ██║
  #  ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/arr/radarr:/config
      - ${MEDIA_PATH}/arr:/arr
    ports:
      - "7878:7878"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7878"]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - black-sea
      - proxy

  radarr-anime:
    image: linuxserver/radarr:latest
    container_name: radarr-anime
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/arr/radarr-anime:/config
      - ${MEDIA_PATH}/arr:/arr
    ports:
      - "7879:7878"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7878" ]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - black-sea
      - proxy

  #  ███████╗ ██████╗ ███╗   ██╗ █████╗ ██████╗ ██████╗
  #  ██╔════╝██╔═══██╗████╗  ██║██╔══██╗██╔══██╗██╔══██╗
  #  ███████╗██║   ██║██╔██╗ ██║███████║██████╔╝██████╔╝
  #  ╚════██║██║   ██║██║╚██╗██║██╔══██║██╔══██╗██╔══██╗
  #  ███████║╚██████╔╝██║ ╚████║██║  ██║██║  ██║██║  ██║
  #  ╚══════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/arr/sonarr:/config
      - ${MEDIA_PATH}/arr:/arr
    ports:
      - "8989:8989"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989"]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - black-sea
      - proxy

  sonarr-anime:
    image: linuxserver/sonarr:latest
    container_name: sonarr-anime
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/arr/sonarr-anime:/config
      - ${MEDIA_PATH}/arr:/arr
    ports:
      - "8990:8989"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8989" ]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - black-sea
      - proxy

  #  ██████╗ ███████╗ ██████╗██╗   ██╗ ██████╗██╗      █████╗ ██████╗ ██████╗
  #  ██╔══██╗██╔════╝██╔════╝╚██╗ ██╔╝██╔════╝██║     ██╔══██╗██╔══██╗██╔══██╗
  #  ██████╔╝█████╗  ██║      ╚████╔╝ ██║     ██║     ███████║██████╔╝██████╔╝
  #  ██╔══██╗██╔══╝  ██║       ╚██╔╝  ██║     ██║     ██╔══██║██╔══██╗██╔══██╗
  #  ██║  ██║███████╗╚██████╗   ██║   ╚██████╗███████╗██║  ██║██║  ██║██║  ██║
  #  ╚═╝  ╚═╝╚══════╝ ╚═════╝   ╚═╝    ╚═════╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    user: "${PUID}:${PGID}"
    volumes:
      - ${CONFIG_PATH}/arr/recyclarr:/config
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    networks:
      - black-sea
      - proxy

  #  ██████╗  █████╗ ███████╗ █████╗ ██████╗ ██████╗
  #  ██╔══██╗██╔══██╗╚══███╔╝██╔══██╗██╔══██╗██╔══██╗
  #  ██████╔╝███████║  ███╔╝ ███████║██████╔╝██████╔╝
  #  ██╔══██╗██╔══██║ ███╔╝  ██╔══██║██╔══██╗██╔══██╗
  #  ██████╔╝██║  ██║███████╗██║  ██║██║  ██║██║  ██║
  #  ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝
  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/arr/bazarr:/config
      - ${MEDIA_PATH}/arr/media/movies:/movies
      - ${MEDIA_PATH}/arr/media/tv:/tv
    ports:
      - "6767:6767"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6767"]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
        - black-sea
        - proxy

  bazarr-anime:
    image: linuxserver/bazarr:latest
    container_name: bazarr-anime
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/arr/bazarr-anime:/config
      - ${MEDIA_PATH}/arr/media/movies-animes:/movies
      - ${MEDIA_PATH}/arr/media/tv-animes:/tv
    ports:
      - "6768:6767"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6767" ]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - black-sea
      - proxy

  #  ██████╗ ██████╗  ██████╗ ██╗    ██╗██╗      █████╗ ██████╗ ██████╗
  #  ██╔══██╗██╔══██╗██╔═══██╗██║    ██║██║     ██╔══██╗██╔══██╗██╔══██╗
  #  ██████╔╝██████╔╝██║   ██║██║ █╗ ██║██║     ███████║██████╔╝██████╔╝
  #  ██╔═══╝ ██╔══██╗██║   ██║██║███╗██║██║     ██╔══██║██╔══██╗██╔══██╗
  #  ██║     ██║  ██║╚██████╔╝╚███╔███╔╝███████╗██║  ██║██║  ██║██║  ██║
  #  ╚═╝     ╚═╝  ╚═╝ ╚═════╝  ╚══╝╚══╝ ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/arr/prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9696"]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - black-sea
      - proxy

  #       ██╗███████╗██╗     ██╗     ██╗   ██╗███████╗██╗███╗   ██╗
  #       ██║██╔════╝██║     ██║     ╚██╗ ██╔╝██╔════╝██║████╗  ██║
  #       ██║█████╗  ██║     ██║      ╚████╔╝ █████╗  ██║██╔██╗ ██║
  #  ██   ██║██╔══╝  ██║     ██║       ╚██╔╝  ██╔══╝  ██║██║╚██╗██║
  #  ╚█████╔╝███████╗███████╗███████╗   ██║   ██║     ██║██║ ╚████║
  #   ╚════╝ ╚══════╝╚══════╝╚══════╝   ╚═╝   ╚═╝     ╚═╝╚═╝  ╚═══╝
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/arr/jellyfin:/config
      - ${MEDIA_PATH}/arr/media/movies:/movies
      - ${MEDIA_PATH}/arr/media/tv:/tvshows
      - ${MEDIA_PATH}/arr/media/movies-animes:/movies-animes
      - ${MEDIA_PATH}/arr/media/tv-animes:/tvshows-animes
    devices:
      - /dev/dri:/dev/dri
    ports:
      - "8096:8096"
      - "7359:7359/udp"
      - "1900:1900/udp"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096"]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - black-sea
      - proxy

  #       ██╗███████╗██╗     ██╗     ██╗   ██╗███████╗███████╗███████╗██████╗ ██████╗
  #       ██║██╔════╝██║     ██║     ╚██╗ ██╔╝██╔════╝██╔════╝██╔════╝██╔══██╗██╔══██╗
  #       ██║█████╗  ██║     ██║      ╚████╔╝ ███████╗█████╗  █████╗  ██████╔╝██████╔╝
  #  ██   ██║██╔══╝  ██║     ██║       ╚██╔╝  ╚════██║██╔══╝  ██╔══╝  ██╔══██╗██╔══██╗
  #  ╚█████╔╝███████╗███████╗███████╗   ██║   ███████║███████╗███████╗██║  ██║██║  ██║
  #   ╚════╝ ╚══════╝╚══════╝╚══════╝   ╚═╝   ╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    ports:
      - "5055:5055"
    volumes:
      - ${CONFIG_PATH}/arr/jellyseerr:/app/config
    restart: unless-stopped
    networks:
      - black-sea
      - proxy

networks:
  black-sea:
    external: true
    name: black-sea
  proxy:
    external: true
    name: proxy
