services:
  #  ██████╗ ████████╗███████╗██████╗  ██████╗ ██████╗  █████╗  ██████╗████████╗██╗   ██╗██╗
  #  ██╔══██╗╚══██╔══╝██╔════╝██╔══██╗██╔═══██╗██╔══██╗██╔══██╗██╔════╝╚══██╔══╝╚██╗ ██╔╝██║
  #  ██████╔╝   ██║   █████╗  ██████╔╝██║   ██║██║  ██║███████║██║        ██║    ╚████╔╝ ██║
  #  ██╔═══╝    ██║   ██╔══╝  ██╔══██╗██║   ██║██║  ██║██╔══██║██║        ██║     ╚██╔╝  ██║
  #  ██║        ██║   ███████╗██║  ██║╚██████╔╝██████╔╝██║  ██║╚██████╗   ██║      ██║   ███████╗
  #  ╚═╝        ╚═╝   ╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝   ╚═╝      ╚═╝   ╚══════╝
  ptero-panel:
    image: ghcr.io/pterodactyl/panel:latest
    container_name: pterodactyl-panel
    restart: always
    ports:
      - "980:80"
    volumes:
      - ${CONFIG_PATH}/pterodactyl/panel/var:/app/var/
      - ${CONFIG_PATH}/pterodactyl/panel/nginx:/etc/nginx/http.d/
      - ${CONFIG_PATH}/pterodactyl/panel/logs:/app/storage/logs
    environment:
      - APP_KEY=${PANEL_KEY}
      - APP_URL=${PANEL_URL}
      - APP_TIMEZONE=${TZ}
      - APP_SERVICE_AUTHOR=${PANEL_AUTHOR}

      - DB_HOST=${DB_HOST}
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_DRIVER=redis
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379

      - TRUSTED_PROXIES= "*"
      - PTERODACTYL_TELEMETRY_ENABLED=False
      - RECAPTCHA_ENABLED=False
      - APP_ENVIRONMENT_ONLY=False
      - SUPERVISOR_HTTP_AUTH=False

      # Mail Settings (Optional - configure if you want email notifications)
    #      - MAIL_DRIVER=smtp
    #      - MAIL_HOST=localhost
    #      - MAIL_PORT=25
    #      - MAIL_USERNAME=
    #      - MAIL_PASSWORD=
    #      - MAIL_ENCRYPTION=true
    #      - MAIL_FROM=noreply@example.com
    #      - MAIL_FROM_NAME=Pterodactyl Panel
    networks:
      - db_network
      - pterodactyl
      - proxy

  # Pterodactyl Wings (Daemon)
  wings0:
    image: ghcr.io/pterodactyl/wings:latest
    container_name: pterodactyl-wings0
    restart: always
    privileged: true
    environment:
      - TZ=${TZ}  # Fixed syntax error
      - WINGS_UID=${PUID}
      - WINGS_GID=${PGID}
      - WINGS_USERNAME=docker_pterodactyl
    volumes:
      # Pterodactyl temp directory - DO NOT CHANGE THIS
      - /tmp/pterodactyl/:/tmp/pterodactyl/

      # Pterodactyl var directories - DO NOT CHANGE THESE
      - /var/lib/pterodactyl/:/var/lib/pterodactyl/
      - /var/log/pterodactyl/:/var/log/pterodactyl/

      # Docker access (required for Wings) - DO NOT CHANGE THESE
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers/:/var/lib/docker/containers/

      # Wings persistent data on TrueNAS
      - ${CONFIG_PATH}/pterodactyl/wings/etc:/etc/pterodactyl/

      # Optional: Large file storage (backups, archives) on HDD
      - ${MEDIA_HDD_PATH}/pterodactyl/backups:/var/lib/pterodactyl/backups/
    ports:
      - "2022:2022"     # SFTP
    networks:
      - wings0
      - proxy

networks:
  pterodactyl:
    external: true
    driver: bridge
    name: pterodactyl
  wings0:
    external: true
    driver: bridge
    name: wings0
    ipam:
        config:
            - subnet: "172.16.50.0/24"
  db_network:
    external: true
    name: db_network
  proxy:
    external: true
    name: proxy
