debug: false
uuid: abcd1234-5678-90ab-cdef-1234567890ab # This UUID should be unique for each Wings instance. You get this from Config page inside Node in Pterodactyl Panel.
token_id: abcdefghijklmnopqrs # This token_id should be unique for each Wings instance. You get this from Config page inside Node in Pterodactyl Panel.
token: abcdefghijklmnopqrstuvwxyz1234567890 # This token should be unique and secure. You get this from Config page inside Node in Pterodactyl Panel.
api:
  host: 0.0.0.0
  port: 443
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/wings0.yours.duckdns.org/fullchain.pem
    key: /etc/letsencrypt/live/wings0.yours.duckdns.org/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://ptero.yours.duckdns.org'
docker:
  network:
    interface: 172.16.50.1
    dns:
      - 192.168.1.1 # Replace with your DNS server, e.g., your router or a public DNS like
      - 1.0.0.1 # cloudflare DNS
    name: wings0
    ispn: false
    driver: bridge
    network_mode: wings0
    is_internal: false
    enable_icc: true
    network_mtu: 9000 # Set to 9000 for Jumbo Frames, can drop to 1500 if you have issues
    interfaces:
      v4:
        subnet: 172.16.50.0/24
        gateway: 172.16.50.1
      v6:
        subnet: fdd0:0:0:5::/64
        gateway: fdd0:0:0:5::1
allowed_mounts: []
allowed_origins: []
allow_cors_private_network: false
ignore_panel_config_updates: false